image: atlassian/docker-release-maker:latest

pipelines:
  custom:
    create-release-base-3:
      - step:
          services:
            - docker
          script:
            - export BASE_VERSION='3'
            - export DEFAULT_RELEASE='true'
            - export DOCKER_REPO='dchevell/crowd'
            - export DOCKERFILE_VERSION_ARG='CROWD_VERSION'
            - export MAC_PRODUCT_KEY='crowd'
            - export TAG_SUFFIXES='alpine'
            - docker login --username ${DOCKER_USERNAME} --password ${DOCKER_PASSWORD}
            - python /usr/src/app/run.py --create
  branches:
    base-3:
      - step:
          services:
            - docker
          script:
            - export BASE_VERSION='3'
            - export DEFAULT_RELEASE='true'
            - export DOCKER_REPO='dchevell/crowd'
            - export DOCKERFILE_VERSION_ARG='CROWD_VERSION'
            - export MAC_PRODUCT_KEY='crowd'
            - export TAG_SUFFIXES='alpine'
            - docker login --username ${DOCKER_USERNAME} --password ${DOCKER_PASSWORD}
            - python /usr/src/app/run.py --update